name: Allure Report Python

on:
  push:
    branches:
      - scooter-tests

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          pytest --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Upload Allure Archive
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-history
